"""
Shell-resolved Antisymmetric Ornstein--Uhlenbeck field simulator.

Model on a periodic LxL lattice with two even variables X_i=(u_i, v_i):

    dX_i = [
        -gamma X_i
        + omega0 R X_i
        + sum_s a_s sum_{delta in S_s} w_s(delta) R (X_{i+delta} - X_i)
    ] dt
    + sqrt(2 T) dW_i,

where

    R = [[0, -1],
         [1,  0]].

Equivalently, for each shell s,

    v_i^(s) = a_s R (K_s X_i - c_s X_i),
    c_s = sum_delta w_s(delta),

where K_s X_i = sum_delta w_s(delta) X_{i+delta}.

Interpretation:
    - gamma: local relaxation rate toward X_i=0.
    - omega0: local irreversible torque at each site.
    - a_s: shell-resolved antisymmetric relative coupling.
    - S_s: non-overlapping annular shell of lattice offsets.
    - w_s(delta): shell weights.

For symmetric shells, w_s(delta)=w_s(-delta), the relative shell operator
Q_s = K_s - c_s I is symmetric in space. Since R is antisymmetric, all
relative shell velocities are generated by skew-symmetric OU operators. Thus
continuous-time stability is controlled by gamma > 0, and the stationary
covariance remains

    C = (T/gamma) I.

Important EPR convention:
    The shell-wise stochastic entropy increment is defined pathwise as

        dS_s ~= (1/T) sum_i v_i^(s)(X_mid) dot dX_i,

    where v_i^(s) = a_s R sum_delta w_s(delta)(X_{i+delta}-X_i).

    This is the signed contribution from the relative shell-X_i interaction
    to the total stochastic entropy production. These shell contributions add
    pathwise to the total irreversible entropy increment, but individual shell
    rates need not be nonnegative because different irreversible components can
    interfere or cancel.

The code also reports a theoretical EPR Gram matrix G_ab = <v_a dot v_b>/T
for components a,b = local, shell0, shell1, ... . The signed pathwise component
rate is sum_b G_ab; the nonnegative self activity is G_aa; and the total EPR is
sum_ab G_ab.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

try:
    from tqdm import trange
except ImportError:
    trange = range


Offset = Tuple[int, int]


# ======================================================================
# Data structures
# ======================================================================

@dataclass(frozen=True)
class Shell:
    """One non-overlapping annular shell."""

    name: str
    offsets: Tuple[Offset, ...]
    weights: np.ndarray
    amplitude: float  # antisymmetric shell amplitude a_s

    def __post_init__(self) -> None:
        if len(self.offsets) == 0:
            raise ValueError(f"Shell {self.name!r} has no offsets.")
        if len(self.offsets) != len(self.weights):
            raise ValueError("offsets and weights must have the same length.")
        if not np.all(np.isfinite(self.weights)):
            raise ValueError("weights contain non-finite values.")


@dataclass
class ShellOps:
    """Precomputed FFT kernel for one shell."""

    shell: Shell
    kernel_hat: np.ndarray  # rfftn of circular kernel


# ======================================================================
# Rotation and weight helpers
# ======================================================================

def rotate90(x: np.ndarray) -> np.ndarray:
    """Apply R=[[0,-1],[1,0]] to the last dimension of x."""
    return np.stack((-x[..., 1], x[..., 0]), axis=-1)


def _normalize_weights(weights: np.ndarray, mode: str) -> np.ndarray:
    """Normalize shell weights."""
    mode = mode.lower()
    if mode in {"mean", "average", "sum"}:
        denom = float(np.sum(weights))
        if denom == 0.0:
            raise ValueError("Cannot mean-normalize weights with zero sum.")
        return weights / denom

    if mode in {"none", "raw"}:
        return weights
    raise ValueError("weight_normalization must be one of {'mean', 'l2', 'none'}.")


# ======================================================================
# Shell construction
# ======================================================================

def make_annular_shells(
    radii: Sequence[float],
    amplitudes: Sequence[float],
    *,
    weight_normalization: str = "mean",
) -> List[Shell]:
    """
    Build non-overlapping annular lattice shells.

    radii defines upper bounds [R1, R2, ...].

    shell 0 contains 0 < r <= R1.

    For the relative interaction sum_delta w_delta (X_{i+delta}-X_i),
    weight_normalization="mean" is usually the most physical choice because
    it makes the shell term compare X_i with a shell average.

    """
    radii = list(map(float, radii))
    amplitudes = list(map(float, amplitudes))

    if len(radii) != len(amplitudes):
        raise ValueError("radii and amplitudes must have the same length.")
    if len(radii) == 0:
        raise ValueError("At least one radius is required.")
    if any(r <= 0 for r in radii):
        raise ValueError("radii must be positive.")
    if any(r2 <= r1 for r1, r2 in zip(radii, radii[1:])):
        raise ValueError("radii must be strictly increasing.")

    rmax = int(np.ceil(radii[-1]))
    shells: List[Shell] = []
    lower = 0.0

    for k, (upper, amp) in enumerate(zip(radii, amplitudes)):
        offsets: List[Offset] = []

        for dy in range(-rmax, rmax + 1):
            for dx in range(-rmax, rmax + 1):
                r = float(np.hypot(dy, dx))

                inside = lower < r <= upper
                if inside:
                    offsets.append((dy, dx))

        if not offsets:
            raise ValueError(f"No lattice offsets found for shell {k}: ({lower}, {upper}].")

        weights = np.ones(len(offsets), dtype=np.float64)
        weights = _normalize_weights(weights, weight_normalization)

        shells.append(
            Shell(
                name=f"S{k}_r({lower:g},{upper:g}]",
                offsets=tuple(offsets),
                weights=weights,
                amplitude=float(amp),
            )
        )
        lower = upper

    return shells


# ======================================================================
# FFT-based shell operations
# ======================================================================

def build_shell_ops(L: int, shells: Sequence[Shell]) -> List[ShellOps]:
    """Precompute FFT kernels for all shells."""
    if L <= 0:
        raise ValueError("L must be positive.")

    ops: List[ShellOps] = []

    for sh in shells:
        kernel = np.zeros((L, L), dtype=np.float64)

        for (dy, dx), w in zip(sh.offsets, sh.weights):
            # Circular kernel for out[i] = sum_delta w_delta field[i + delta].
            # Circular convolution uses out[i] = sum_j kernel[j] field[i - j],
            # so set j = -delta.
            kernel[(-dy) % L, (-dx) % L] += w

        ops.append(ShellOps(shell=sh, kernel_hat=np.fft.rfftn(kernel, axes=(0, 1))))

    return ops


def shell_convolution_fft(field: np.ndarray, op: ShellOps) -> np.ndarray:
    """Compute sum_delta w_delta field[i+delta] with periodic boundaries."""
    return np.fft.irfftn(
        np.fft.rfftn(field, axes=(0, 1)) * op.kernel_hat,
        s=field.shape,
        axes=(0, 1),
    ).real


# ======================================================================
# Kernel analysis helpers
# ======================================================================

def shell_weight_sum(sh: Shell) -> float:
    """Return c_s = sum_delta w_s(delta)."""
    return float(np.sum(sh.weights))


def shell_center_weight(sh: Shell) -> float:
    """Return the total weight assigned to offset (0,0), usually zero."""
    return float(sum(w for delta, w in zip(sh.offsets, sh.weights) if delta == (0, 0)))


def relative_shell_kernel_dict(sh: Shell) -> Dict[Offset, float]:
    """
    Return the scalar kernel q_s for Q_s X_i = sum_delta q_s(delta) X_{i+delta}.

    For relative coupling,
        Q_s = K_s - c_s I,
        c_s = sum_delta w_s(delta).
    Therefore q_s(delta)=w_s(delta) for shell offsets and
        q_s(0,0) += -c_s.

    If the center offset is included in the shell, its direct term cancels
    because w_0 X_i - w_0 X_i = 0.
    """
    q: Dict[Offset, float] = {}
    for delta, w in zip(sh.offsets, sh.weights):
        q[delta] = q.get(delta, 0.0) + float(w)
    q[(0, 0)] = q.get((0, 0), 0.0) - shell_weight_sum(sh)
    return {delta: val for delta, val in q.items() if abs(val) > 1e-15}


def kernel_inner(q1: Dict[Offset, float], q2: Dict[Offset, float]) -> float:
    """Inner product per lattice site between two translation-invariant kernels."""
    if len(q1) > len(q2):
        q1, q2 = q2, q1
    return float(sum(v * q2.get(k, 0.0) for k, v in q1.items()))


# ======================================================================
# Velocity fields
# ======================================================================

def local_torque_velocity(x: np.ndarray, omega0: float) -> np.ndarray:
    """Compute omega0 R X_i."""
    if omega0 == 0.0:
        return np.zeros_like(x, dtype=np.float64)
    return float(omega0) * rotate90(x)


def relative_displacement_by_shell(x: np.ndarray, op: ShellOps) -> np.ndarray:
    """
    Compute sum_delta w_delta (X_{i+delta} - X_i); x shape (L,L,2).

    With weight_normalization="mean", this is shell_average(X)_i - X_i.
    """
    sh = op.shell
    c = shell_weight_sum(sh)

    conv_u = shell_convolution_fft(x[..., 0], op)
    conv_v = shell_convolution_fft(x[..., 1], op)

    out = np.empty_like(x, dtype=np.float64)
    out[..., 0] = conv_u - c * x[..., 0]
    out[..., 1] = conv_v - c * x[..., 1]
    return out


def antisymmetric_velocity_by_shell(x: np.ndarray, op: ShellOps) -> np.ndarray:
    """
    Compute the relative shell irreversible velocity

        v_i^(s) = a_s sum_delta w_delta R (X_{i+delta} - X_i).

    This is the shell-X_i interaction velocity, not an absolute X_j torque.
    """
    sh = op.shell

    if sh.amplitude == 0.0:
        return np.zeros_like(x, dtype=np.float64)

    diff = relative_displacement_by_shell(x, op)
    return float(sh.amplitude) * rotate90(diff)


def irreversible_velocity_total(
    x: np.ndarray,
    ops: Sequence[ShellOps],
    omega0: float = 0.0,
) -> np.ndarray:
    """Compute omega0 R X_i + sum_s a_s sum_delta w_delta R(X_{i+delta}-X_i)."""
    v = local_torque_velocity(x, omega0)

    for op in ops:
        if op.shell.amplitude != 0.0:
            v = v + antisymmetric_velocity_by_shell(x, op)

    return v


def drift(
    x: np.ndarray,
    ops: Sequence[ShellOps],
    gamma: float,
    omega0: float = 0.0,
) -> np.ndarray:
    """
    Full drift:
        -gamma X + omega0 R X + sum_s a_s sum_delta w_delta R(X_{i+delta}-X_i).
    """
    if gamma <= 0:
        raise ValueError("gamma must be positive for a stable OU process.")

    return -gamma * x + irreversible_velocity_total(x, ops, omega0=omega0)


# ======================================================================
# Theoretical EPR
# ======================================================================

def theoretical_epr_gram(
    L: int,
    shells: Sequence[Shell],
    gamma: float,
    omega0: float,
) -> np.ndarray:
    """
    Analytic EPR Gram matrix G_ab = <v_a dot v_b>/T.

    Components are ordered as [local, shell0, shell1, ...].

    For symmetric shells, C=(T/gamma)I and
        G_ab = (2 L^2 / gamma) coeff_a coeff_b <q_a, q_b>,
    where q_local(delta)=1_{delta=0}, q_s is the relative shell kernel, and
    <q_a,q_b> = sum_delta q_a(delta) q_b(delta).
    """
    if gamma <= 0:
        raise ValueError("gamma must be positive.")

    N = L * L
    coeffs = [float(omega0)] + [float(sh.amplitude) for sh in shells]
    kernels: List[Dict[Offset, float]] = [{(0, 0): 1.0}]
    kernels.extend(relative_shell_kernel_dict(sh) for sh in shells)

    n_comp = len(coeffs)
    gram = np.zeros((n_comp, n_comp), dtype=np.float64)
    prefactor = 2.0 * N / gamma

    for a in range(n_comp):
        for b in range(a, n_comp):
            val = prefactor * coeffs[a] * coeffs[b] * kernel_inner(kernels[a], kernels[b])
            gram[a, b] = val
            gram[b, a] = val

    return gram


def theoretical_epr_self_components(
    L: int,
    shells: Sequence[Shell],
    gamma: float,
    omega0: float,
) -> np.ndarray:
    """Return nonnegative self activities diag(G), ordered as [local, shell0, ...]."""
    return np.diag(theoretical_epr_gram(L, shells, gamma, omega0)).copy()


def theoretical_epr_path_components(
    L: int,
    shells: Sequence[Shell],
    gamma: float,
    omega0: float,
) -> np.ndarray:
    """
    Return signed pathwise component rates sum_b G_ab, ordered as [local, shell0, ...].

    These components add to the total EPR but can be negative individually.
    """
    return theoretical_epr_gram(L, shells, gamma, omega0).sum(axis=1)


def theoretical_local_epr(L: int, omega0: float, gamma: float) -> float:
    """Analytic local self activity when considered alone."""
    N = L * L
    return float((2.0 * N / gamma) * omega0**2)


def theoretical_epr_by_shell(L: int, shells: Sequence[Shell], gamma: float) -> np.ndarray:
    """
    Analytic nonnegative self activity per relative shell, ignoring cross terms.

    For shell s,
        Sdot_s,self = (2 L^2/gamma) a_s^2 sum_delta q_s(delta)^2,
    where q_s is the relative kernel for X_j-X_i.
    """
    N = L * L
    return np.asarray(
        [
            (2.0 * N / gamma)
            * (float(sh.amplitude) ** 2)
            * kernel_inner(relative_shell_kernel_dict(sh), relative_shell_kernel_dict(sh))
            for sh in shells
        ],
        dtype=np.float64,
    )


def theoretical_total_epr(L: int, shells: Sequence[Shell], gamma: float, omega0: float) -> float:
    """Analytic total EPR rate including local/shell and shell/shell cross terms."""
    return float(theoretical_epr_gram(L, shells, gamma, omega0).sum())


# ======================================================================
# Pathwise EPR increments
# ======================================================================

def pathwise_local_epr_increment(
    x0: np.ndarray,
    x1: np.ndarray,
    omega0: float,
    T: float,
) -> float:
    """
    Midpoint Stratonovich estimate of local torque entropy increment:
        dS_local ~= (1/T) sum_i [omega0 R X_mid]_i dot dX_i.

    This is the signed local component of the total stochastic EP.
    """
    if omega0 == 0.0:
        return 0.0

    x_mid = 0.5 * (x0 + x1)
    dx = x1 - x0
    vel = local_torque_velocity(x_mid, omega0)
    return float(np.sum(vel * dx) / T)


def pathwise_shell_epr_increment(
    x0: np.ndarray,
    x1: np.ndarray,
    ops: Sequence[ShellOps],
    T: float,
) -> np.ndarray:
    """
    Midpoint Stratonovich estimate of relative shell entropy increments:

        dS_s ~= (1/T) sum_i [a_s sum_delta w_delta R(X_{i+delta}-X_i)]_mid dot dX_i.

    These are signed interaction contributions. Dividing mean(dS_s) by dt
    estimates the shell-X_i pathwise EPR contribution rates.
    """
    x_mid = 0.5 * (x0 + x1)
    dx = x1 - x0

    inc = []
    for op in ops:
        vel_s = antisymmetric_velocity_by_shell(x_mid, op)
        inc.append(float(np.sum(vel_s * dx) / T))

    return np.asarray(inc, dtype=np.float64)


def pathwise_total_epr_increment(
    x0: np.ndarray,
    x1: np.ndarray,
    ops: Sequence[ShellOps],
    omega0: float,
    T: float,
) -> float:
    """Midpoint Stratonovich estimate of the total stochastic EP increment."""
    x_mid = 0.5 * (x0 + x1)
    dx = x1 - x0
    vel = irreversible_velocity_total(x_mid, ops, omega0=omega0)
    return float(np.sum(vel * dx) / T)


# ======================================================================
# Main simulation function
# ======================================================================

def simulate(
    *,
    L: int = 32,
    radii: Sequence[float] = (1, 2, 4, 8),
    amplitudes: Sequence[float] = (0.0, 0.0, 0.6, 0.0),
    gamma: float = 1.0,
    omega0: float = 0.0,
    T: float = 1.0,
    dt: float = 1e-3,
    n_steps: int = 50_000,
    burn_steps: int = 5_000,
    sample_every: int = 10,
    seed: int = 0,
    record_trajectory: bool = True,
    weight_normalization: str = "mean",
    x0: Optional[np.ndarray] = None,
    show_progress: bool = True,
) -> Dict[str, Any]:
    """
    Simulate the local + relative antisymmetric shell OU field with Euler--Maruyama.

    Parameters
    ----------
    L:
        Linear lattice size.
    radii:
        Upper radii of annular shells.
    amplitudes:
        Relative antisymmetric shell amplitudes a_s.
    gamma:
        Local damping rate.
    omega0:
        Local torque amplitude.
    T:
        Noise temperature.
    dt:
        Time step.
    n_steps:
        Number of production steps after burn-in.
    burn_steps:
        Burn-in steps.
    sample_every:
        Save trajectory and cumulative stochastic EP every this many production steps.
    weight_normalization:
        "mean" makes each shell term compare X_i with the shell average.
        "none" leaves raw unit weights.
    x0:
        Optional initial condition of shape (L,L,2).
    show_progress:
        If True, show tqdm progress bars.
    """
    if gamma <= 0:
        raise ValueError("gamma must be positive.")
    if T <= 0:
        raise ValueError("T must be positive.")
    if dt <= 0:
        raise ValueError("dt must be positive.")
    if n_steps <= 0:
        raise ValueError("n_steps must be positive.")
    if burn_steps < 0:
        raise ValueError("burn_steps must be non-negative.")
    if sample_every <= 0:
        raise ValueError("sample_every must be positive.")

    rng = np.random.default_rng(seed)
    shells = make_annular_shells(
        radii,
        amplitudes,
        weight_normalization=weight_normalization,
    )
    ops = build_shell_ops(L, shells)

    if x0 is None:
        # Exact stationary marginal distribution for symmetric relative antisymmetric OU model.
        x = rng.normal(loc=0.0, scale=np.sqrt(T / gamma), size=(L, L, 2))
    else:
        x = np.asarray(x0, dtype=np.float64).copy()
        if x.shape != (L, L, 2):
            raise ValueError(f"x0 must have shape {(L, L, 2)}, got {x.shape}.")

    noise_scale = np.sqrt(2.0 * T * dt)

    # Burn-in
    burn_iter = trange(burn_steps, desc="Burn-in", leave=False) if show_progress else range(burn_steps)
    for _ in burn_iter:
        x = x + drift(x, ops, gamma, omega0=omega0) * dt + noise_scale * rng.normal(size=x.shape)

    # Production
    samples: List[np.ndarray] = []
    sample_steps: List[int] = []
    sample_times: List[float] = []

    epr_inc_local: List[float] = []
    epr_inc_shell: List[np.ndarray] = []
    epr_inc_total: List[float] = []

    prod_iter = trange(n_steps, desc="Simulating", leave=False) if show_progress else range(n_steps)
    for step in prod_iter:
        x_before = x.copy()
        x_after = (
            x_before
            + drift(x_before, ops, gamma, omega0=omega0) * dt
            + noise_scale * rng.normal(size=x_before.shape)
        )

        inc_local = pathwise_local_epr_increment(x_before, x_after, omega0, T)
        inc_shell = pathwise_shell_epr_increment(x_before, x_after, ops, T)
        inc_total = float(inc_local + inc_shell.sum())

        epr_inc_local.append(inc_local)
        epr_inc_shell.append(inc_shell)
        epr_inc_total.append(inc_total)

        x = x_after

        if record_trajectory and (step % sample_every == 0):
            samples.append(x.copy())
            sample_steps.append(step + 1)
            sample_times.append((step + 1) * dt)

    epr_inc_local_arr = np.asarray(epr_inc_local, dtype=np.float64)
    epr_inc_shell_arr = np.asarray(epr_inc_shell, dtype=np.float64)
    epr_inc_total_arr = np.asarray(epr_inc_total, dtype=np.float64)

    epr_rate_est_local = float(epr_inc_local_arr.mean() / dt)
    epr_rate_sem_local = float(epr_inc_local_arr.std(ddof=1) / np.sqrt(n_steps) / dt)

    epr_rate_est_shell = epr_inc_shell_arr.mean(axis=0) / dt
    epr_rate_sem_shell = epr_inc_shell_arr.std(axis=0, ddof=1) / np.sqrt(n_steps) / dt

    epr_rate_est_total = float(epr_inc_total_arr.mean() / dt)
    epr_rate_sem_total = float(epr_inc_total_arr.std(ddof=1) / np.sqrt(n_steps) / dt)

    epr_theory_gram = theoretical_epr_gram(L, shells, gamma, omega0)
    epr_theory_self_components = np.diag(epr_theory_gram).copy()
    epr_theory_path_components = epr_theory_gram.sum(axis=1)

    return {
        "trajectory": np.asarray(samples) if record_trajectory else None,
        "shells": shells,
        "ops": ops,

        # One-step stochastic EP increments.
        "epr_increment_by_step_local": epr_inc_local_arr,
        "epr_increment_by_step_shell": epr_inc_shell_arr,
        "epr_increment_by_step_total": epr_inc_total_arr,

        # Estimated signed pathwise EPR rates.
        "epr_rate_est_local": epr_rate_est_local,
        "epr_rate_sem_local": epr_rate_sem_local,
        "epr_rate_est_by_shell": epr_rate_est_shell,
        "epr_rate_sem_by_shell": epr_rate_sem_shell,
        "epr_rate_est_total": epr_rate_est_total,
        "epr_rate_sem_total": epr_rate_sem_total,

        # Theory: self activity is nonneg; path component is signed and additive.
        "epr_rate_theory_gram": epr_theory_gram,
        "epr_rate_theory_self_local": float(epr_theory_self_components[0]),
        "epr_rate_theory_self_by_shell": epr_theory_self_components[1:],
        "epr_rate_theory_path_local": float(epr_theory_path_components[0]),
        "epr_rate_theory_path_by_shell": epr_theory_path_components[1:],
        "epr_rate_theory_total": float(epr_theory_gram.sum()),

        "params": {
            "L": L,
            "radii": tuple(radii),
            "amplitudes": tuple(amplitudes),
            "gamma": gamma,
            "omega0": omega0,
            "T": T,
            "dt": dt,
            "n_steps": n_steps,
            "burn_steps": burn_steps,
            "sample_every": sample_every,
            "seed": seed,
            "record_trajectory": record_trajectory,
            "weight_normalization": weight_normalization,
            "interaction": "relative_Xj_minus_Xi",
        },
    }
